services:

  postgres_tripex:
    image: postgres:latest
    container_name: postgres_tripex
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Iopjklbnm890
      POSTGRES_DB: tripex_db
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  
  redis_tripex:
    image: redis:latest
    ports:
      - "6381:6379"
    volumes:
      - "redis-data:/data"

volumes:
  redis-data:
  postgres-data:
  