services:
  authdb:
    image: postgres:latest
    container_name: authdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: Vlad
      POSTGRES_PASSWORD: postgres2025
      POSTGRES_DB: auth
    volumes:
      - auth_data:/var/lib/postgresql/data

volumes:
  auth_data:  
