services:
  profiles-redis-db:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: on-failure
    volumes:
      - "profiles-redis-data:/data"
        
  posts-redis-db:
    image: redis:latest
    ports:
      - "6381:6379"
    restart: on-failure
    volumes:
      - "posts-redis-data:/data"
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure

volumes:
  profiles-redis-data:
  posts-redis-data:
